---

- name: "install backend server" 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait until target is available (timeout=600s)"
      wait_for_connection:
  roles:
    - install-nodejs-environment
    - install-pm2
    - configure-pm2-backend-udapeople

