---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "install nodejs environment."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes